### ISSUE TITLE
Plugin will not install/sync to project - license not found

### ISSUE THREAD

**Issue by ccamarillo** [mplodowski/logout-plugin-public#3]
**Describe the bug**
I am working on an OctoberCMS 3.0 project.  I have purchased the Logout plugin and added it to my project.  However, when I run `php artisan plugin:install Renatio.Logout`, I get this error:
```
A product license for "renatio/logout-plugin" could not be found
```
`php artisan project:sync` also ignores the plugin and does not pull it down.

**To Reproduce**
1. Purchase and install the plugin at OctoberCMS.com
2. Go to your project command line and run `php artisan plugin:install Renatio.Logout`

**Expected behavior**
I expect the plugin to be installed after running the install command.  There should be a plugin folder for this plugin.

**October version**
3.3.22

**Plugin version**
5.0.3

**Additional context**
The plugin was purchased today.

**Comment by mplodowski** [comment]
Hi,

each October project has a license. When you a buy plugin you attach it to the project. Please double check that your project license is the same as the project where you attached my plugin.

Please go to your projects: https://octobercms.com/account/project/dashboard

Then select the project where you bought my plugin. The plugin should be listed on plugins tab.

Then on the right side there is a button "Display license". Click it and copy license key.

Then on your terminal run following command inside project root:

`php artisan project:set <license key>`

Now try to run:

`php artisan project:sync`

If this is not working then contact October support team at: hello@octobercms.com
